name: Build and deploy module
on:
  push:
    tags:
      - v*

permissions:
  contents: write
jobs:
  release:
    name: "Publish package to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.5.0
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build-module
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
